##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Classify structured data with feature columns

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/structured_data/feature_columns">
    <img src="https://www.tensorflow.org/images/tf_logo_32px.png" />
    View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/colab_logo_32px.png" />
    Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />
    View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/structured_data/feature_columns.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

> Warning: The `tf.feature_columns` module described in this tutorial is not recommended for new code. [Keras preprocessing layers](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers) cover this functionality, for migration instructions see the [Migrating feature columns](../../guide/migrate/migrating_feature_columns.ipynb) guide. The `tf.feature_columns` module was designed for use with TF1 `Estimators`. It does fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities.

This tutorial demonstrates how to classify structured data (e.g. tabular data in a CSV). We will use [Keras](https://www.tensorflow.org/guide/keras) to define the model, and `tf.feature_column` as a bridge to map from columns in a CSV to features used to train the model. This tutorial contains complete code to:

* Load a CSV file using [Pandas](https://pandas.pydata.org/).
* Build an input pipeline to batch and shuffle the rows using [tf.data](https://www.tensorflow.org/guide/datasets).
* Map from columns in the CSV to features used to train the model using feature columns.
* Build, train, and evaluate a model using Keras.

## The Dataset

We will use a simplified version of the PetFinder [dataset](https://www.kaggle.com/c/petfinder-adoption-prediction). There are several thousand rows in the CSV. Each row describes a pet, and each column describes an attribute. We will use this information to predict the speed at which the pet will be adopted.

Following is a description of this dataset. Notice there are both numeric and categorical columns. There is a free text column which we will not use in this tutorial.

Column | Description| Feature Type | Data Type
------------|--------------------|----------------------|-----------------
Type | Type of animal (Dog, Cat) | Categorical | string
Age |  Age of the pet | Numerical | integer
Breed1 | Primary breed of the pet | Categorical | string
Color1 | Color 1 of pet | Categorical | string
Color2 | Color 2 of pet | Categorical | string
MaturitySize | Size at maturity | Categorical | string
FurLength | Fur length | Categorical | string
Vaccinated | Pet has been vaccinated | Categorical | string
Sterilized | Pet has been sterilized | Categorical | string
Health | Health Condition | Categorical | string
Fee | Adoption Fee | Numerical | integer
Description | Profile write-up for this pet | Text | string
PhotoAmt | Total uploaded photos for this pet | Numerical | integer
AdoptionSpeed | Speed of adoption | Classification | integer

## Import TensorFlow and other libraries

In [2]:
!pip install sklearn

In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

## Use Pandas to create a dataframe

[Pandas](https://pandas.pydata.org/) is a Python library with many helpful utilities for loading and working with structured data. We will use Pandas to download the dataset from a URL, and load it into a dataframe.

In [4]:
import pathlib

dataset_url = 'http://storage.googleapis.com/download.tensorflow.org/data/petfinder-mini.zip'
csv_file = 'datasets/petfinder-mini/petfinder-mini.csv'

tf.keras.utils.get_file('petfinder_mini.zip', dataset_url,
                        extract=True, cache_dir='.')
dataframe = pd.read_csv(csv_file)

  16384/1668792 [..............................] - ETA: 0s

1671168/1668792 [==============================] - 0s 0us/step


1679360/1668792 [==============================] - 0s 0us/step


In [5]:
dataframe.head()

Type  Age                Breed1  Gender Color1    Color2 MaturitySize  \
0  Cat    3                 Tabby    Male  Black     White        Small   
1  Cat    1  Domestic Medium Hair    Male  Black     Brown       Medium   
2  Dog    1           Mixed Breed    Male  Brown     White       Medium   
3  Dog    4           Mixed Breed  Female  Black     Brown       Medium   
4  Dog    1           Mixed Breed    Male  Black  No Color       Medium   

  FurLength Vaccinated Sterilized   Health  Fee  \
0     Short         No         No  Healthy  100   
1    Medium   Not Sure   Not Sure  Healthy    0   
2    Medium        Yes         No  Healthy    0   
3     Short        Yes         No  Healthy  150   
4     Short         No         No  Healthy    0   

                                         Description  PhotoAmt  AdoptionSpeed  
0  Nibble is a 3+ month old ball of cuteness. He ...         1              2  
1  I just found it alone yesterday near my apartm...         2              0  
2  Their pregnant mother was dumped by her irresp...         7              3  
3  Good guard dog, very alert, active, obedience ...         8              2  
4  This handsome yet cute boy is up for adoption....         3              2

## Create target variable

The task in the original dataset is to predict the speed at which a pet will be adopted (e.g., in the first week, the first month, the first three months, and so on). Let's simplify this for our tutorial. Here, we will transform this into a binary classification problem, and simply predict whether the pet was adopted, or not.

After modifying the label column, 0 will indicate the pet was not adopted, and 1 will indicate it was.

In [6]:
# In the original dataset "4" indicates the pet was not adopted.
dataframe['target'] = np.where(dataframe['AdoptionSpeed']==4, 0, 1)

# Drop un-used columns.
dataframe = dataframe.drop(columns=['AdoptionSpeed', 'Description'])

## Split the dataframe into train, validation, and test

The dataset we downloaded was a single CSV file. We will split this into train, validation, and test sets.

In [7]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

7383 train examples
1846 validation examples
2308 test examples


## Create an input pipeline using tf.data

Next, we will wrap the dataframes with [tf.data](https://www.tensorflow.org/guide/datasets). This will enable us  to use feature columns as a bridge to map from the columns in the Pandas dataframe to features used to train the model. If we were working with a very large CSV file (so large that it does not fit into memory), we would use tf.data to read it from disk directly. That is not covered in this tutorial.

In [8]:
# A utility method to create a tf.data dataset from a Pandas Dataframe
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [9]:
batch_size = 5 # A small batch sized is used for demonstration purposes
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

2021-08-12 05:35:14.232343: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


2021-08-12 05:35:14.240910: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-12 05:35:14.241897: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-12 05:35:14.244078: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-12 05:35:14.244713: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA 

## Understand the input pipeline

Now that we have created the input pipeline, let's call it to see the format of the data it returns. We have used a small batch size to keep the output readable.

In [10]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['Age'])
  print('A batch of targets:', label_batch )

Every feature: ['Type', 'Age', 'Breed1', 'Gender', 'Color1', 'Color2', 'MaturitySize', 'FurLength', 'Vaccinated', 'Sterilized', 'Health', 'Fee', 'PhotoAmt']
A batch of ages: tf.Tensor([3 1 7 3 2], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([0 0 0 1 1], shape=(5,), dtype=int64)


We can see that the dataset returns a dictionary of column names (from the dataframe) that map to column values from rows in the dataframe.

## Demonstrate several types of feature columns
TensorFlow provides many types of feature columns. In this section, we will create several types of feature columns, and demonstrate how they transform a column from the dataframe.

In [11]:
# We will use this batch to demonstrate several types of feature columns
example_batch = next(iter(train_ds))[0]

In [12]:
# A utility method to create a feature column
# and to transform a batch of data
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### Numeric columns
The output of a feature column becomes the input to the model (using the demo function defined above, we will be able to see exactly how each column from the dataframe is transformed). A [numeric column](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column) is the simplest type of column. It is used to represent real valued features. When using this column, your model will receive the column value from the dataframe unchanged.

In [13]:
photo_count = feature_column.numeric_column('PhotoAmt')
demo(photo_count)

[[1.]
 [1.]
 [6.]
 [2.]
 [1.]]


In the PetFinder dataset, most columns from the dataframe are categorical.

### Bucketized columns
Often, you don't want to feed a number directly into the model, but instead split its value into different categories based on numerical ranges. Consider raw data that represents a person's age. Instead of representing age as a numeric column, we could split the age into several buckets using a [bucketized column](https://www.tensorflow.org/api_docs/python/tf/feature_column/bucketized_column). Notice the one-hot values below describe which age range each row matches.

In [14]:
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 3, 5])
demo(age_buckets)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


### Categorical columns
In this dataset, Type is represented as a string (e.g. 'Dog', or 'Cat'). We cannot feed strings directly to a model. Instead, we must first map them to numeric values. The categorical vocabulary columns provide a way to represent strings as a one-hot vector (much like you have seen above with age buckets). The vocabulary can be passed as a list using [categorical_column_with_vocabulary_list](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list), or loaded from a file using [categorical_column_with_vocabulary_file](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file).

In [15]:
animal_type = feature_column.categorical_column_with_vocabulary_list(
      'Type', ['Cat', 'Dog'])

animal_type_one_hot = feature_column.indicator_column(animal_type)
demo(animal_type_one_hot)

[[0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


### Embedding columns
Suppose instead of having just a few possible strings, we have thousands (or more) values per category. For a number of reasons, as the number of categories grow large, it becomes infeasible to train a neural network using one-hot encodings. We can use an embedding column to overcome this limitation. Instead of representing the data as a one-hot vector of many dimensions, an [embedding column](https://www.tensorflow.org/api_docs/python/tf/feature_column/embedding_column) represents that data as a lower-dimensional, dense vector in which each cell can contain any number, not just 0 or 1. The size of the embedding (8, in the example below) is a parameter that must be tuned.

Key point: using an embedding column is best when a categorical column has many possible values. We are using one here for demonstration purposes, so you have a complete example you can modify for a different dataset in the future.

In [16]:
# Notice the input to the embedding column is the categorical column
# we previously created
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
demo(breed1_embedding)

[[-0.29149556  0.14527628 -0.14971544 -0.03371305 -0.18008554 -0.1355874
   0.07782566 -0.25116035]
 [ 0.17409092 -0.5352956   0.17639622  0.14120959  0.06684854 -0.1125162
  -0.29759833  0.13288419]
 [-0.54347     0.12352454  0.2705486   0.38947123  0.03339173 -0.00610726
  -0.07117687 -0.01907084]
 [ 0.42062348  0.62146646 -0.16005716  0.08512937  0.19332875  0.24204789
  -0.03377973  0.47258624]
 [ 0.06813324  0.28805184  0.02640903 -0.05147618  0.6982352  -0.06342584
  -0.1650086  -0.06650425]]


### Hashed feature columns

Another way to represent a categorical column with a large number of values is to use a [categorical_column_with_hash_bucket](https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket). This feature column calculates a hash value of the input, then selects one of the `hash_bucket_size` buckets to encode a string. When using this column, you do not need to provide the vocabulary, and you can choose to make the number of hash_buckets significantly smaller than the number of actual categories to save space.

Key point: An important downside of this technique is that there may be collisions in which different strings are mapped to the same bucket. In practice, this can work well for some datasets regardless.

In [17]:
breed1_hashed = feature_column.categorical_column_with_hash_bucket(
      'Breed1', hash_bucket_size=10)
demo(feature_column.indicator_column(breed1_hashed))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Crossed feature columns
Combining features into a single feature, better known as [feature crosses](https://developers.google.com/machine-learning/glossary/#feature_cross), enables a model to learn separate weights for each combination of features. Here, we will create a new feature that is the cross of Age and Type. Note that `crossed_column` does not build the full table of all possible combinations (which could be very large). Instead, it is backed by a `hashed_column`, so you can choose how large the table is.

In [18]:
crossed_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


## Choose which columns to use
We have seen how to use several types of feature columns. Now we will use them to train a model. The goal of this tutorial is to show you the complete code (e.g. mechanics) needed to work with feature columns. We have selected a few columns to train our model below arbitrarily.

Key point: If your aim is to build an accurate model, try a larger dataset of your own, and think carefully about which features are the most meaningful to include, and how they should be represented.

In [19]:
feature_columns = []

# numeric cols
for header in ['PhotoAmt', 'Fee', 'Age']:
  feature_columns.append(feature_column.numeric_column(header))

In [20]:
# bucketized cols
age = feature_column.numeric_column('Age')
age_buckets = feature_column.bucketized_column(age, boundaries=[1, 2, 3, 4, 5])
feature_columns.append(age_buckets)

In [21]:
# indicator_columns
indicator_column_names = ['Type', 'Color1', 'Color2', 'Gender', 'MaturitySize',
                          'FurLength', 'Vaccinated', 'Sterilized', 'Health']
for col_name in indicator_column_names:
  categorical_column = feature_column.categorical_column_with_vocabulary_list(
      col_name, dataframe[col_name].unique())
  indicator_column = feature_column.indicator_column(categorical_column)
  feature_columns.append(indicator_column)

In [22]:
# embedding columns
breed1 = feature_column.categorical_column_with_vocabulary_list(
      'Breed1', dataframe.Breed1.unique())
breed1_embedding = feature_column.embedding_column(breed1, dimension=8)
feature_columns.append(breed1_embedding)

In [23]:
# crossed columns
age_type_feature = feature_column.crossed_column([age_buckets, animal_type], hash_bucket_size=100)
feature_columns.append(feature_column.indicator_column(age_type_feature))

### Create a feature layer
Now that we have defined our feature columns, we will use a [DenseFeatures](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures) layer to input them to our Keras model.

In [24]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

Earlier, we used a small batch size to demonstrate how feature columns worked. We create a new input pipeline with a larger batch size.

In [25]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## Create, compile, and train the model

In [26]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dropout(.1),
  layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              metrics=['accuracy'])

model.fit(train_ds,
          validation_data=val_ds,
          epochs=10)

Epoch 1/10
Consider rewriting this model with the Functional API.


Consider rewriting this model with the Functional API.


2021-08-12 05:35:16.625423: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


  1/231 [..............................] - ETA: 6:09 - loss: 1.1628 - accuracy: 0.2500

  8/231 [>.............................] - ETA: 1s - loss: 0.8257 - accuracy: 0.5312  

 15/231 [>.............................] - ETA: 1s - loss: 0.7262 - accuracy: 0.6375

 22/231 [=>............................] - ETA: 1s - loss: 0.8170 - accuracy: 0.6534

 29/231 [==>...........................] - ETA: 1s - loss: 0.7768 - accuracy: 0.6724

 37/231 [===>..........................] - ETA: 1s - loss: 0.7374 - accuracy: 0.6765

 44/231 [====>.........................] - ETA: 1s - loss: 0.7329 - accuracy: 0.6747

 52/231 [=====>........................] - ETA: 1s - loss: 0.7421 - accuracy: 0.6737

 59/231 [======>.......................] - ETA: 1s - loss: 0.7427 - accuracy: 0.6764

 65/231 [=======>......................] - ETA: 1s - loss: 0.7429 - accuracy: 0.6793

 72/231 [========>.....................] - ETA: 1s - loss: 0.7362 - accuracy: 0.6753

 78/231 [=========>....................] - ETA: 1s - loss: 0.7262 - accuracy: 0.6747

 85/231 [==========>...................] - ETA: 1s - loss: 0.7148 - accuracy: 0.6746

 92/231 [==========>...................] - ETA: 1s - loss: 0.7079 - accuracy: 0.6766

 99/231 [===========>..................] - ETA: 1s - loss: 0.7067 - accuracy: 0.6799

106/231 [============>.................] - ETA: 0s - loss: 0.7126 - accuracy: 0.6754

113/231 [=============>................] - ETA: 0s - loss: 0.7088 - accuracy: 0.6728

120/231 [==============>...............] - ETA: 0s - loss: 0.7030 - accuracy: 0.6734

127/231 [===============>..............] - ETA: 0s - loss: 0.7020 - accuracy: 0.6762

134/231 [================>.............] - ETA: 0s - loss: 0.7021 - accuracy: 0.6763

141/231 [=================>............] - ETA: 0s - loss: 0.7060 - accuracy: 0.6784

148/231 [==================>...........] - ETA: 0s - loss: 0.7079 - accuracy: 0.6791

155/231 [===================>..........] - ETA: 0s - loss: 0.6996 - accuracy: 0.6800

162/231 [====================>.........] - ETA: 0s - loss: 0.6969 - accuracy: 0.6806

169/231 [====================>.........] - ETA: 0s - loss: 0.6924 - accuracy: 0.6825

176/231 [=====================>........] - ETA: 0s - loss: 0.6882 - accuracy: 0.6824

183/231 [======================>.......] - ETA: 0s - loss: 0.6829 - accuracy: 0.6846

190/231 [=======================>......] - ETA: 0s - loss: 0.6770 - accuracy: 0.6868

197/231 [========================>.....] - ETA: 0s - loss: 0.6724 - accuracy: 0.6877

204/231 [=========================>....] - ETA: 0s - loss: 0.6673 - accuracy: 0.6878

211/231 [==========================>...] - ETA: 0s - loss: 0.6642 - accuracy: 0.6882

218/231 [===========================>..] - ETA: 0s - loss: 0.6592 - accuracy: 0.6904

225/231 [============================>.] - ETA: 0s - loss: 0.6541 - accuracy: 0.6914

Consider rewriting this model with the Functional API.


231/231 [==============================] - 4s 11ms/step - loss: 0.6513 - accuracy: 0.6929 - val_loss: 0.5530 - val_accuracy: 0.7172


Epoch 2/10
  1/231 [..............................] - ETA: 10s - loss: 0.4133 - accuracy: 0.7500

  8/231 [>.............................] - ETA: 1s - loss: 0.5224 - accuracy: 0.7305 

 15/231 [>.............................] - ETA: 1s - loss: 0.5237 - accuracy: 0.7583

 22/231 [=>............................] - ETA: 1s - loss: 0.5451 - accuracy: 0.7443

 29/231 [==>...........................] - ETA: 1s - loss: 0.5507 - accuracy: 0.7522

 36/231 [===>..........................] - ETA: 1s - loss: 0.5577 - accuracy: 0.7465

 43/231 [====>.........................] - ETA: 1s - loss: 0.5485 - accuracy: 0.7376

 50/231 [=====>........................] - ETA: 1s - loss: 0.5620 - accuracy: 0.7287

 57/231 [======>.......................] - ETA: 1s - loss: 0.5630 - accuracy: 0.7242

 63/231 [=======>......................] - ETA: 1s - loss: 0.5764 - accuracy: 0.7188

 70/231 [========>.....................] - ETA: 1s - loss: 0.5783 - accuracy: 0.7156

 77/231 [=========>....................] - ETA: 1s - loss: 0.5920 - accuracy: 0.7155

 84/231 [=========>....................] - ETA: 1s - loss: 0.6021 - accuracy: 0.7057

 90/231 [==========>...................] - ETA: 1s - loss: 0.6038 - accuracy: 0.7076

 97/231 [===========>..................] - ETA: 1s - loss: 0.6020 - accuracy: 0.7113

104/231 [============>.................] - ETA: 0s - loss: 0.6044 - accuracy: 0.7124

110/231 [=============>................] - ETA: 0s - loss: 0.6045 - accuracy: 0.7105

116/231 [==============>...............] - ETA: 0s - loss: 0.6025 - accuracy: 0.7109

123/231 [==============>...............] - ETA: 0s - loss: 0.5985 - accuracy: 0.7106

130/231 [===============>..............] - ETA: 0s - loss: 0.5956 - accuracy: 0.7096

137/231 [================>.............] - ETA: 0s - loss: 0.5934 - accuracy: 0.7096

144/231 [=================>............] - ETA: 0s - loss: 0.5885 - accuracy: 0.7103

151/231 [==================>...........] - ETA: 0s - loss: 0.5880 - accuracy: 0.7092

158/231 [===================>..........] - ETA: 0s - loss: 0.5878 - accuracy: 0.7093

165/231 [====================>.........] - ETA: 0s - loss: 0.5868 - accuracy: 0.7108

172/231 [=====================>........] - ETA: 0s - loss: 0.5836 - accuracy: 0.7138

179/231 [======================>.......] - ETA: 0s - loss: 0.5812 - accuracy: 0.7149

186/231 [=======================>......] - ETA: 0s - loss: 0.5791 - accuracy: 0.7144

193/231 [========================>.....] - ETA: 0s - loss: 0.5794 - accuracy: 0.7139

200/231 [========================>.....] - ETA: 0s - loss: 0.5770 - accuracy: 0.7134

207/231 [=========================>....] - ETA: 0s - loss: 0.5775 - accuracy: 0.7130

214/231 [==========================>...] - ETA: 0s - loss: 0.5753 - accuracy: 0.7128

221/231 [===========================>..] - ETA: 0s - loss: 0.5739 - accuracy: 0.7130

228/231 [============================>.] - ETA: 0s - loss: 0.5736 - accuracy: 0.7135

231/231 [==============================] - 2s 9ms/step - loss: 0.5726 - accuracy: 0.7142 - val_loss: 0.5061 - val_accuracy: 0.7481


Epoch 3/10
  1/231 [..............................] - ETA: 10s - loss: 0.4839 - accuracy: 0.7812

  8/231 [>.............................] - ETA: 1s - loss: 0.4754 - accuracy: 0.7109 

 15/231 [>.............................] - ETA: 1s - loss: 0.4949 - accuracy: 0.6979

 22/231 [=>............................] - ETA: 1s - loss: 0.4912 - accuracy: 0.7060

 29/231 [==>...........................] - ETA: 1s - loss: 0.5033 - accuracy: 0.7166

 36/231 [===>..........................] - ETA: 1s - loss: 0.5226 - accuracy: 0.7109

 42/231 [====>.........................] - ETA: 1s - loss: 0.5301 - accuracy: 0.7039

 48/231 [=====>........................] - ETA: 1s - loss: 0.5286 - accuracy: 0.7038

 54/231 [======>.......................] - ETA: 1s - loss: 0.5246 - accuracy: 0.7049

 60/231 [======>.......................] - ETA: 1s - loss: 0.5320 - accuracy: 0.7083

 66/231 [=======>......................] - ETA: 1s - loss: 0.5265 - accuracy: 0.7121

 73/231 [========>.....................] - ETA: 1s - loss: 0.5292 - accuracy: 0.7115

 80/231 [=========>....................] - ETA: 1s - loss: 0.5289 - accuracy: 0.7105

 87/231 [==========>...................] - ETA: 1s - loss: 0.5279 - accuracy: 0.7116

 94/231 [===========>..................] - ETA: 1s - loss: 0.5248 - accuracy: 0.7148

101/231 [============>.................] - ETA: 1s - loss: 0.5239 - accuracy: 0.7157

107/231 [============>.................] - ETA: 1s - loss: 0.5221 - accuracy: 0.7179

113/231 [=============>................] - ETA: 0s - loss: 0.5187 - accuracy: 0.7218

119/231 [==============>...............] - ETA: 0s - loss: 0.5188 - accuracy: 0.7224

125/231 [===============>..............] - ETA: 0s - loss: 0.5212 - accuracy: 0.7212

131/231 [================>.............] - ETA: 0s - loss: 0.5210 - accuracy: 0.7216

137/231 [================>.............] - ETA: 0s - loss: 0.5189 - accuracy: 0.7219

144/231 [=================>............] - ETA: 0s - loss: 0.5176 - accuracy: 0.7222

151/231 [==================>...........] - ETA: 0s - loss: 0.5183 - accuracy: 0.7221

158/231 [===================>..........] - ETA: 0s - loss: 0.5180 - accuracy: 0.7235

165/231 [====================>.........] - ETA: 0s - loss: 0.5174 - accuracy: 0.7229

172/231 [=====================>........] - ETA: 0s - loss: 0.5175 - accuracy: 0.7226

178/231 [======================>.......] - ETA: 0s - loss: 0.5180 - accuracy: 0.7212

184/231 [======================>.......] - ETA: 0s - loss: 0.5183 - accuracy: 0.7221

190/231 [=======================>......] - ETA: 0s - loss: 0.5184 - accuracy: 0.7222

196/231 [========================>.....] - ETA: 0s - loss: 0.5176 - accuracy: 0.7224

202/231 [=========================>....] - ETA: 0s - loss: 0.5177 - accuracy: 0.7237

208/231 [==========================>...] - ETA: 0s - loss: 0.5173 - accuracy: 0.7245

215/231 [==========================>...] - ETA: 0s - loss: 0.5162 - accuracy: 0.7249

221/231 [===========================>..] - ETA: 0s - loss: 0.5158 - accuracy: 0.7244

227/231 [============================>.] - ETA: 0s - loss: 0.5154 - accuracy: 0.7244

231/231 [==============================] - 2s 10ms/step - loss: 0.5145 - accuracy: 0.7249 - val_loss: 0.5066 - val_accuracy: 0.7557


Epoch 4/10
  1/231 [..............................] - ETA: 10s - loss: 0.3887 - accuracy: 0.8125

  7/231 [..............................] - ETA: 2s - loss: 0.5789 - accuracy: 0.6786 

 13/231 [>.............................] - ETA: 1s - loss: 0.5386 - accuracy: 0.7091

 19/231 [=>............................] - ETA: 1s - loss: 0.5189 - accuracy: 0.7204

 25/231 [==>...........................] - ETA: 1s - loss: 0.5124 - accuracy: 0.7262

 31/231 [===>..........................] - ETA: 1s - loss: 0.5142 - accuracy: 0.7298

 37/231 [===>..........................] - ETA: 1s - loss: 0.5157 - accuracy: 0.7238

 44/231 [====>.........................] - ETA: 1s - loss: 0.5113 - accuracy: 0.7266

 51/231 [=====>........................] - ETA: 1s - loss: 0.5092 - accuracy: 0.7286

 58/231 [======>.......................] - ETA: 1s - loss: 0.5027 - accuracy: 0.7338

 65/231 [=======>......................] - ETA: 1s - loss: 0.5055 - accuracy: 0.7284

 72/231 [========>.....................] - ETA: 1s - loss: 0.5047 - accuracy: 0.7257

 78/231 [=========>....................] - ETA: 1s - loss: 0.5025 - accuracy: 0.7280

 85/231 [==========>...................] - ETA: 1s - loss: 0.5009 - accuracy: 0.7298

 92/231 [==========>...................] - ETA: 1s - loss: 0.5005 - accuracy: 0.7306

 99/231 [===========>..................] - ETA: 1s - loss: 0.5003 - accuracy: 0.7311

106/231 [============>.................] - ETA: 1s - loss: 0.5012 - accuracy: 0.7285

113/231 [=============>................] - ETA: 0s - loss: 0.4997 - accuracy: 0.7282

120/231 [==============>...............] - ETA: 0s - loss: 0.4972 - accuracy: 0.7312

127/231 [===============>..............] - ETA: 0s - loss: 0.5019 - accuracy: 0.7315

134/231 [================>.............] - ETA: 0s - loss: 0.4987 - accuracy: 0.7334

141/231 [=================>............] - ETA: 0s - loss: 0.4954 - accuracy: 0.7349

147/231 [==================>...........] - ETA: 0s - loss: 0.4984 - accuracy: 0.7330

153/231 [==================>...........] - ETA: 0s - loss: 0.5011 - accuracy: 0.7328

159/231 [===================>..........] - ETA: 0s - loss: 0.5000 - accuracy: 0.7321

165/231 [====================>.........] - ETA: 0s - loss: 0.5013 - accuracy: 0.7314

171/231 [=====================>........] - ETA: 0s - loss: 0.5034 - accuracy: 0.7319

177/231 [=====================>........] - ETA: 0s - loss: 0.5055 - accuracy: 0.7293

184/231 [======================>.......] - ETA: 0s - loss: 0.5061 - accuracy: 0.7293

191/231 [=======================>......] - ETA: 0s - loss: 0.5036 - accuracy: 0.7313

198/231 [========================>.....] - ETA: 0s - loss: 0.5052 - accuracy: 0.7311

205/231 [=========================>....] - ETA: 0s - loss: 0.5043 - accuracy: 0.7326

212/231 [==========================>...] - ETA: 0s - loss: 0.5048 - accuracy: 0.7317

219/231 [===========================>..] - ETA: 0s - loss: 0.5019 - accuracy: 0.7342

226/231 [============================>.] - ETA: 0s - loss: 0.5013 - accuracy: 0.7349

231/231 [==============================] - 2s 10ms/step - loss: 0.5018 - accuracy: 0.7345 - val_loss: 0.4926 - val_accuracy: 0.7405


Epoch 5/10
  1/231 [..............................] - ETA: 9s - loss: 0.3842 - accuracy: 0.8438

  7/231 [..............................] - ETA: 1s - loss: 0.4095 - accuracy: 0.7946

 14/231 [>.............................] - ETA: 1s - loss: 0.4308 - accuracy: 0.7790

 21/231 [=>............................] - ETA: 1s - loss: 0.4445 - accuracy: 0.7708

 27/231 [==>...........................] - ETA: 1s - loss: 0.4617 - accuracy: 0.7535

 34/231 [===>..........................] - ETA: 1s - loss: 0.4768 - accuracy: 0.7426

 40/231 [====>.........................] - ETA: 1s - loss: 0.4734 - accuracy: 0.7437

 47/231 [=====>........................] - ETA: 1s - loss: 0.4739 - accuracy: 0.7414

 54/231 [======>.......................] - ETA: 1s - loss: 0.4773 - accuracy: 0.7425

 61/231 [======>.......................] - ETA: 1s - loss: 0.4762 - accuracy: 0.7428

 68/231 [=======>......................] - ETA: 1s - loss: 0.4793 - accuracy: 0.7413

 75/231 [========>.....................] - ETA: 1s - loss: 0.4802 - accuracy: 0.7442

 82/231 [=========>....................] - ETA: 1s - loss: 0.4796 - accuracy: 0.7458

 88/231 [==========>...................] - ETA: 1s - loss: 0.4844 - accuracy: 0.7440

 95/231 [===========>..................] - ETA: 1s - loss: 0.4858 - accuracy: 0.7424

101/231 [============>.................] - ETA: 1s - loss: 0.4913 - accuracy: 0.7389

108/231 [=============>................] - ETA: 0s - loss: 0.4947 - accuracy: 0.7387

115/231 [=============>................] - ETA: 0s - loss: 0.4978 - accuracy: 0.7345

122/231 [==============>...............] - ETA: 0s - loss: 0.4980 - accuracy: 0.7321

128/231 [===============>..............] - ETA: 0s - loss: 0.4945 - accuracy: 0.7349

135/231 [================>.............] - ETA: 0s - loss: 0.4951 - accuracy: 0.7345

142/231 [=================>............] - ETA: 0s - loss: 0.4959 - accuracy: 0.7355

148/231 [==================>...........] - ETA: 0s - loss: 0.4945 - accuracy: 0.7367

154/231 [===================>..........] - ETA: 0s - loss: 0.4911 - accuracy: 0.7378

161/231 [===================>..........] - ETA: 0s - loss: 0.4902 - accuracy: 0.7382

168/231 [====================>.........] - ETA: 0s - loss: 0.4920 - accuracy: 0.7381

175/231 [=====================>........] - ETA: 0s - loss: 0.4901 - accuracy: 0.7402

182/231 [======================>.......] - ETA: 0s - loss: 0.4921 - accuracy: 0.7382

189/231 [=======================>......] - ETA: 0s - loss: 0.4934 - accuracy: 0.7356

196/231 [========================>.....] - ETA: 0s - loss: 0.4938 - accuracy: 0.7344

203/231 [=========================>....] - ETA: 0s - loss: 0.4956 - accuracy: 0.7334

210/231 [==========================>...] - ETA: 0s - loss: 0.4959 - accuracy: 0.7342

217/231 [===========================>..] - ETA: 0s - loss: 0.4983 - accuracy: 0.7332

224/231 [============================>.] - ETA: 0s - loss: 0.4975 - accuracy: 0.7321

231/231 [==============================] - 2s 9ms/step - loss: 0.4950 - accuracy: 0.7332 - val_loss: 0.4997 - val_accuracy: 0.7600


Epoch 6/10
  1/231 [..............................] - ETA: 10s - loss: 0.3969 - accuracy: 0.8438

  8/231 [>.............................] - ETA: 1s - loss: 0.4683 - accuracy: 0.7773 

 15/231 [>.............................] - ETA: 1s - loss: 0.4617 - accuracy: 0.7812

 22/231 [=>............................] - ETA: 1s - loss: 0.4702 - accuracy: 0.7670

 29/231 [==>...........................] - ETA: 1s - loss: 0.4782 - accuracy: 0.7597

 36/231 [===>..........................] - ETA: 1s - loss: 0.4764 - accuracy: 0.7569

 43/231 [====>.........................] - ETA: 1s - loss: 0.4777 - accuracy: 0.7507

 50/231 [=====>........................] - ETA: 1s - loss: 0.4720 - accuracy: 0.7531

 56/231 [======>.......................] - ETA: 1s - loss: 0.4697 - accuracy: 0.7561

 62/231 [=======>......................] - ETA: 1s - loss: 0.4691 - accuracy: 0.7550

 68/231 [=======>......................] - ETA: 1s - loss: 0.4705 - accuracy: 0.7532

 75/231 [========>.....................] - ETA: 1s - loss: 0.4678 - accuracy: 0.7529

 82/231 [=========>....................] - ETA: 1s - loss: 0.4684 - accuracy: 0.7527

 89/231 [==========>...................] - ETA: 1s - loss: 0.4717 - accuracy: 0.7493

 96/231 [===========>..................] - ETA: 1s - loss: 0.4739 - accuracy: 0.7493

103/231 [============>.................] - ETA: 0s - loss: 0.4723 - accuracy: 0.7503

110/231 [=============>................] - ETA: 0s - loss: 0.4762 - accuracy: 0.7466

117/231 [==============>...............] - ETA: 0s - loss: 0.4747 - accuracy: 0.7489

123/231 [==============>...............] - ETA: 0s - loss: 0.4753 - accuracy: 0.7485

129/231 [===============>..............] - ETA: 0s - loss: 0.4745 - accuracy: 0.7466

136/231 [================>.............] - ETA: 0s - loss: 0.4781 - accuracy: 0.7449

142/231 [=================>............] - ETA: 0s - loss: 0.4775 - accuracy: 0.7447

149/231 [==================>...........] - ETA: 0s - loss: 0.4780 - accuracy: 0.7445

156/231 [===================>..........] - ETA: 0s - loss: 0.4762 - accuracy: 0.7460

163/231 [====================>.........] - ETA: 0s - loss: 0.4790 - accuracy: 0.7462

170/231 [=====================>........] - ETA: 0s - loss: 0.4805 - accuracy: 0.7458

177/231 [=====================>........] - ETA: 0s - loss: 0.4808 - accuracy: 0.7458

185/231 [=======================>......] - ETA: 0s - loss: 0.4817 - accuracy: 0.7449

191/231 [=======================>......] - ETA: 0s - loss: 0.4835 - accuracy: 0.7436

198/231 [========================>.....] - ETA: 0s - loss: 0.4846 - accuracy: 0.7418

205/231 [=========================>....] - ETA: 0s - loss: 0.4844 - accuracy: 0.7413

212/231 [==========================>...] - ETA: 0s - loss: 0.4839 - accuracy: 0.7419

219/231 [===========================>..] - ETA: 0s - loss: 0.4849 - accuracy: 0.7423

226/231 [============================>.] - ETA: 0s - loss: 0.4846 - accuracy: 0.7420

231/231 [==============================] - 2s 9ms/step - loss: 0.4852 - accuracy: 0.7425 - val_loss: 0.4907 - val_accuracy: 0.7443


Epoch 7/10
  1/231 [..............................] - ETA: 10s - loss: 0.4615 - accuracy: 0.8438

  8/231 [>.............................] - ETA: 1s - loss: 0.4576 - accuracy: 0.7539 

 15/231 [>.............................] - ETA: 1s - loss: 0.4622 - accuracy: 0.7521

 22/231 [=>............................] - ETA: 1s - loss: 0.4576 - accuracy: 0.7528

 29/231 [==>...........................] - ETA: 1s - loss: 0.4670 - accuracy: 0.7478

 36/231 [===>..........................] - ETA: 1s - loss: 0.4606 - accuracy: 0.7543

 43/231 [====>.........................] - ETA: 1s - loss: 0.4538 - accuracy: 0.7602

 50/231 [=====>........................] - ETA: 1s - loss: 0.4563 - accuracy: 0.7613

 58/231 [======>.......................] - ETA: 1s - loss: 0.4611 - accuracy: 0.7538

 65/231 [=======>......................] - ETA: 1s - loss: 0.4598 - accuracy: 0.7534

 72/231 [========>.....................] - ETA: 1s - loss: 0.4655 - accuracy: 0.7522

 79/231 [=========>....................] - ETA: 1s - loss: 0.4709 - accuracy: 0.7484

 86/231 [==========>...................] - ETA: 1s - loss: 0.4766 - accuracy: 0.7398

 93/231 [===========>..................] - ETA: 1s - loss: 0.4771 - accuracy: 0.7392

100/231 [===========>..................] - ETA: 0s - loss: 0.4757 - accuracy: 0.7412

107/231 [============>.................] - ETA: 0s - loss: 0.4792 - accuracy: 0.7395

114/231 [=============>................] - ETA: 0s - loss: 0.4784 - accuracy: 0.7415

121/231 [==============>...............] - ETA: 0s - loss: 0.4771 - accuracy: 0.7438

128/231 [===============>..............] - ETA: 0s - loss: 0.4802 - accuracy: 0.7400

135/231 [================>.............] - ETA: 0s - loss: 0.4801 - accuracy: 0.7389

142/231 [=================>............] - ETA: 0s - loss: 0.4794 - accuracy: 0.7414

149/231 [==================>...........] - ETA: 0s - loss: 0.4791 - accuracy: 0.7399

156/231 [===================>..........] - ETA: 0s - loss: 0.4814 - accuracy: 0.7404

163/231 [====================>.........] - ETA: 0s - loss: 0.4829 - accuracy: 0.7398

170/231 [=====================>........] - ETA: 0s - loss: 0.4818 - accuracy: 0.7393

177/231 [=====================>........] - ETA: 0s - loss: 0.4799 - accuracy: 0.7401

184/231 [======================>.......] - ETA: 0s - loss: 0.4795 - accuracy: 0.7408

191/231 [=======================>......] - ETA: 0s - loss: 0.4791 - accuracy: 0.7415

198/231 [========================>.....] - ETA: 0s - loss: 0.4796 - accuracy: 0.7420

205/231 [=========================>....] - ETA: 0s - loss: 0.4791 - accuracy: 0.7430

213/231 [==========================>...] - ETA: 0s - loss: 0.4793 - accuracy: 0.7430

220/231 [===========================>..] - ETA: 0s - loss: 0.4781 - accuracy: 0.7443

227/231 [============================>.] - ETA: 0s - loss: 0.4794 - accuracy: 0.7427

231/231 [==============================] - 2s 9ms/step - loss: 0.4791 - accuracy: 0.7436 - val_loss: 0.4965 - val_accuracy: 0.7411


Epoch 8/10
  1/231 [..............................] - ETA: 9s - loss: 0.5598 - accuracy: 0.7500

  8/231 [>.............................] - ETA: 1s - loss: 0.4644 - accuracy: 0.7656

 15/231 [>.............................] - ETA: 1s - loss: 0.4799 - accuracy: 0.7437

 22/231 [=>............................] - ETA: 1s - loss: 0.4668 - accuracy: 0.7500

 29/231 [==>...........................] - ETA: 1s - loss: 0.4737 - accuracy: 0.7532

 35/231 [===>..........................] - ETA: 1s - loss: 0.4673 - accuracy: 0.7696

 42/231 [====>.........................] - ETA: 1s - loss: 0.4775 - accuracy: 0.7552

 49/231 [=====>........................] - ETA: 1s - loss: 0.4765 - accuracy: 0.7545

 56/231 [======>.......................] - ETA: 1s - loss: 0.4783 - accuracy: 0.7573

 63/231 [=======>......................] - ETA: 1s - loss: 0.4809 - accuracy: 0.7550

 70/231 [========>.....................] - ETA: 1s - loss: 0.4924 - accuracy: 0.7473

 77/231 [=========>....................] - ETA: 1s - loss: 0.4978 - accuracy: 0.7427

 84/231 [=========>....................] - ETA: 1s - loss: 0.4942 - accuracy: 0.7414

 91/231 [==========>...................] - ETA: 1s - loss: 0.4923 - accuracy: 0.7428

 97/231 [===========>..................] - ETA: 1s - loss: 0.4913 - accuracy: 0.7429

104/231 [============>.................] - ETA: 0s - loss: 0.4931 - accuracy: 0.7425

111/231 [=============>................] - ETA: 0s - loss: 0.4862 - accuracy: 0.7472

118/231 [==============>...............] - ETA: 0s - loss: 0.4881 - accuracy: 0.7468

125/231 [===============>..............] - ETA: 0s - loss: 0.4869 - accuracy: 0.7480

132/231 [================>.............] - ETA: 0s - loss: 0.4876 - accuracy: 0.7479

139/231 [=================>............] - ETA: 0s - loss: 0.4864 - accuracy: 0.7469

146/231 [=================>............] - ETA: 0s - loss: 0.4843 - accuracy: 0.7476

153/231 [==================>...........] - ETA: 0s - loss: 0.4839 - accuracy: 0.7480

160/231 [===================>..........] - ETA: 0s - loss: 0.4859 - accuracy: 0.7453

167/231 [====================>.........] - ETA: 0s - loss: 0.4823 - accuracy: 0.7474

174/231 [=====================>........] - ETA: 0s - loss: 0.4813 - accuracy: 0.7493

181/231 [======================>.......] - ETA: 0s - loss: 0.4806 - accuracy: 0.7488

189/231 [=======================>......] - ETA: 0s - loss: 0.4810 - accuracy: 0.7465

196/231 [========================>.....] - ETA: 0s - loss: 0.4798 - accuracy: 0.7471

203/231 [=========================>....] - ETA: 0s - loss: 0.4779 - accuracy: 0.7485

210/231 [==========================>...] - ETA: 0s - loss: 0.4775 - accuracy: 0.7487

217/231 [===========================>..] - ETA: 0s - loss: 0.4772 - accuracy: 0.7488

224/231 [============================>.] - ETA: 0s - loss: 0.4779 - accuracy: 0.7479

231/231 [==============================] - ETA: 0s - loss: 0.4779 - accuracy: 0.7471

231/231 [==============================] - 2s 9ms/step - loss: 0.4779 - accuracy: 0.7471 - val_loss: 0.4956 - val_accuracy: 0.7356


Epoch 9/10
  1/231 [..............................] - ETA: 9s - loss: 0.4468 - accuracy: 0.7812

  8/231 [>.............................] - ETA: 1s - loss: 0.4545 - accuracy: 0.7500

 14/231 [>.............................] - ETA: 1s - loss: 0.4439 - accuracy: 0.7612

 21/231 [=>............................] - ETA: 1s - loss: 0.4444 - accuracy: 0.7708

 28/231 [==>...........................] - ETA: 1s - loss: 0.4441 - accuracy: 0.7746

 35/231 [===>..........................] - ETA: 1s - loss: 0.4343 - accuracy: 0.7821

 42/231 [====>.........................] - ETA: 1s - loss: 0.4350 - accuracy: 0.7835

 49/231 [=====>........................] - ETA: 1s - loss: 0.4488 - accuracy: 0.7704

 56/231 [======>.......................] - ETA: 1s - loss: 0.4505 - accuracy: 0.7690

 63/231 [=======>......................] - ETA: 1s - loss: 0.4508 - accuracy: 0.7624

 70/231 [========>.....................] - ETA: 1s - loss: 0.4561 - accuracy: 0.7621

 77/231 [=========>....................] - ETA: 1s - loss: 0.4570 - accuracy: 0.7585

 84/231 [=========>....................] - ETA: 1s - loss: 0.4567 - accuracy: 0.7600

 90/231 [==========>...................] - ETA: 1s - loss: 0.4527 - accuracy: 0.7628

 97/231 [===========>..................] - ETA: 1s - loss: 0.4553 - accuracy: 0.7626

103/231 [============>.................] - ETA: 1s - loss: 0.4549 - accuracy: 0.7624

110/231 [=============>................] - ETA: 0s - loss: 0.4589 - accuracy: 0.7597

117/231 [==============>...............] - ETA: 0s - loss: 0.4573 - accuracy: 0.7623

124/231 [===============>..............] - ETA: 0s - loss: 0.4582 - accuracy: 0.7618

131/231 [================>.............] - ETA: 0s - loss: 0.4585 - accuracy: 0.7619

138/231 [================>.............] - ETA: 0s - loss: 0.4631 - accuracy: 0.7570

145/231 [=================>............] - ETA: 0s - loss: 0.4656 - accuracy: 0.7537

152/231 [==================>...........] - ETA: 0s - loss: 0.4661 - accuracy: 0.7531

159/231 [===================>..........] - ETA: 0s - loss: 0.4672 - accuracy: 0.7494

166/231 [====================>.........] - ETA: 0s - loss: 0.4665 - accuracy: 0.7491

173/231 [=====================>........] - ETA: 0s - loss: 0.4659 - accuracy: 0.7484

180/231 [======================>.......] - ETA: 0s - loss: 0.4682 - accuracy: 0.7486

187/231 [=======================>......] - ETA: 0s - loss: 0.4706 - accuracy: 0.7458

194/231 [========================>.....] - ETA: 0s - loss: 0.4707 - accuracy: 0.7468

201/231 [=========================>....] - ETA: 0s - loss: 0.4715 - accuracy: 0.7453

208/231 [==========================>...] - ETA: 0s - loss: 0.4718 - accuracy: 0.7452

215/231 [==========================>...] - ETA: 0s - loss: 0.4713 - accuracy: 0.7461

222/231 [===========================>..] - ETA: 0s - loss: 0.4715 - accuracy: 0.7463

229/231 [============================>.] - ETA: 0s - loss: 0.4709 - accuracy: 0.7477

231/231 [==============================] - 2s 9ms/step - loss: 0.4700 - accuracy: 0.7479 - val_loss: 0.4910 - val_accuracy: 0.7394


Epoch 10/10
  1/231 [..............................] - ETA: 9s - loss: 0.3703 - accuracy: 0.7188

  8/231 [>.............................] - ETA: 1s - loss: 0.4684 - accuracy: 0.6836

 16/231 [=>............................] - ETA: 1s - loss: 0.4695 - accuracy: 0.7090

 23/231 [=>............................] - ETA: 1s - loss: 0.4614 - accuracy: 0.7174

 30/231 [==>...........................] - ETA: 1s - loss: 0.4500 - accuracy: 0.7406

 37/231 [===>..........................] - ETA: 1s - loss: 0.4480 - accuracy: 0.7475

 44/231 [====>.........................] - ETA: 1s - loss: 0.4553 - accuracy: 0.7450

 51/231 [=====>........................] - ETA: 1s - loss: 0.4429 - accuracy: 0.7543

 58/231 [======>.......................] - ETA: 1s - loss: 0.4490 - accuracy: 0.7522

 65/231 [=======>......................] - ETA: 1s - loss: 0.4419 - accuracy: 0.7620

 72/231 [========>.....................] - ETA: 1s - loss: 0.4420 - accuracy: 0.7626

 79/231 [=========>....................] - ETA: 1s - loss: 0.4398 - accuracy: 0.7599

 86/231 [==========>...................] - ETA: 1s - loss: 0.4430 - accuracy: 0.7609

 94/231 [===========>..................] - ETA: 1s - loss: 0.4435 - accuracy: 0.7610

101/231 [============>.................] - ETA: 0s - loss: 0.4433 - accuracy: 0.7621

108/231 [=============>................] - ETA: 0s - loss: 0.4439 - accuracy: 0.7639

115/231 [=============>................] - ETA: 0s - loss: 0.4449 - accuracy: 0.7636

122/231 [==============>...............] - ETA: 0s - loss: 0.4474 - accuracy: 0.7613

129/231 [===============>..............] - ETA: 0s - loss: 0.4508 - accuracy: 0.7594

136/231 [================>.............] - ETA: 0s - loss: 0.4520 - accuracy: 0.7597

143/231 [=================>............] - ETA: 0s - loss: 0.4540 - accuracy: 0.7581

150/231 [==================>...........] - ETA: 0s - loss: 0.4578 - accuracy: 0.7556

157/231 [===================>..........] - ETA: 0s - loss: 0.4601 - accuracy: 0.7532

164/231 [====================>.........] - ETA: 0s - loss: 0.4606 - accuracy: 0.7538

172/231 [=====================>........] - ETA: 0s - loss: 0.4626 - accuracy: 0.7518

179/231 [======================>.......] - ETA: 0s - loss: 0.4617 - accuracy: 0.7535

186/231 [=======================>......] - ETA: 0s - loss: 0.4624 - accuracy: 0.7539

193/231 [========================>.....] - ETA: 0s - loss: 0.4616 - accuracy: 0.7536

200/231 [========================>.....] - ETA: 0s - loss: 0.4618 - accuracy: 0.7538

207/231 [=========================>....] - ETA: 0s - loss: 0.4619 - accuracy: 0.7542

214/231 [==========================>...] - ETA: 0s - loss: 0.4633 - accuracy: 0.7529

221/231 [===========================>..] - ETA: 0s - loss: 0.4612 - accuracy: 0.7537

229/231 [============================>.] - ETA: 0s - loss: 0.4609 - accuracy: 0.7537

231/231 [==============================] - 2s 9ms/step - loss: 0.4621 - accuracy: 0.7528 - val_loss: 0.5080 - val_accuracy: 0.7248


In [27]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

 1/73 [..............................] - ETA: 1s - loss: 0.7041 - accuracy: 0.5625

10/73 [===>..........................] - ETA: 0s - loss: 0.5789 - accuracy: 0.6656

19/73 [======>.......................] - ETA: 0s - loss: 0.5465 - accuracy: 0.6891

28/73 [==========>...................] - ETA: 0s - loss: 0.5241 - accuracy: 0.6964

37/73 [==============>...............] - ETA: 0s - loss: 0.5194 - accuracy: 0.6985

46/73 [=================>............] - ETA: 0s - loss: 0.5352 - accuracy: 0.6868

55/73 [=====================>........] - ETA: 0s - loss: 0.5400 - accuracy: 0.6909

65/73 [=========================>....] - ETA: 0s - loss: 0.5414 - accuracy: 0.6894

73/73 [==============================] - 0s 6ms/step - loss: 0.5444 - accuracy: 0.6919


Accuracy 0.6919410824775696


Key point: You will typically see best results with deep learning with much larger and more complex datasets. When working with a small dataset like this one, we recommend using a decision tree or random forest as a strong baseline. The goal of this tutorial is not to train an accurate model, but to demonstrate the mechanics of working with structured data, so you have code to use as a starting point when working with your own datasets in the future.

## Next steps
The best way to learn more about classifying structured data is to try it yourself. We suggest finding another dataset to work with, and training a model to classify it using code similar to the above. To improve accuracy, think carefully about which features to include in your model, and how they should be represented.